language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=3.1

# command to install dependencies
install:
  - cd ./example;
  - pip install -r requirements.txt
  - pip uninstall -y -q django
  - pip install -q Django==$DJANGO_VERSION

# command to run tests
script:
    coverage run --rcfile=$(pwd)/../.coveragerc manage.py test test_chamber.tests --settings=dj.settings.settings -v 2

after_success:
    coveralls
